### ISSUE TITLE
Define a messaging schema

### ISSUE THREAD

**Issue by JosNun** [PulseDevelopmentGroup/go-spy-go#5]
To keep things organized and sorta standardized, we need a schema of sorts for requests being sent over websocket. 

One option is to respond with something similar to what was sent.

```
req: {
    type: "CREATE_GAME",
    data: {
        gameId: "abc123",
        username: "John Doe"
    }
}
```
To confirm that the server got the message, it could respond with something like the following
```
res: {
    type: "CREATE_GAME",
    data: {
        gameId: "abc123",
        username: "John Doe"
    }
}
```

In the event that an error occurred, we could attach an error object to the response.
```
res: {
    type: "CREATE_GAME",
    data: {
        error: "Username already in game",
        gameId: "abc123"
    }
}
```

Another option would be to append "Success" or "Failure" to the response, indicating the status of the request. 
```
res: {
    type: "CREATE_GAME_SUCCESS",
    data: {
        gameId: "abc123",
        username: "John Doe"
    }
}

// OR

{
    type: "CREATE_GAME_FAILURE",
    data: {
        error: "Username already in game",
        gameId: "abc123"
    }
}
```

**EDIT:** I just realized that this feels very [Redux](https://redux.js.org/basics/actions)y, not that that's a bad thing

**Comment by CS-5** [comment]
To cut down on duplicate code, it might make more sense to make the response always include an error, even if nothing is there.

Example response when everything is good.
```
req: {
    type: "CREATE_GAME",
    data: {
        gameId: "abc123",
        username: "John Doe"
    },
    error: {
        code: "200"
        message: "OK"
    }
}
```
Example response when things are bad
```
req: {
    type: "CREATE_GAME",
    data: {
        gameId: "abc123",
        username: "John Doe"
    },
    error: {
        code: "404"
        message: "Resource not found"
    }
}
```

**Comment by JosNun** [comment]
That could work. That increases the payload size, and we'd actually have to check down into the response to check for errors though. Nothing major, but it's still there. Also, how does it cut down on code?

**Comment by CS-5** [comment]
#8 Resolved this (for the most part)
